name: Build nodejs
on:
  push:
    branches:
      - master
    paths:
      - nodejs/*
jobs:
  push:
    name: "images:nodejs"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          file: ./nodejs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/hwalker928/images:nodejs
